// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection;

namespace album_collection.Migrations
{
    [DbContext(typeof(MusicContext))]
    partial class MusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Description = "The fifth studio album and first concept album by American progressive metal band Dream Theater, released on October 26, 1999 through Elektra Records.",
                            Image = "",
                            Name = "Metropolis Pt.2: Scenes from a Memory",
                            Rating = "10/10"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Description = "The fourteenth studio album by American progressive metal band Dream Theater, released on February 22, 2019, and being the band's first release on Inside Out Music.",
                            Image = "",
                            Name = "Distance over Time",
                            Rating = "9/10"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Description = "The debut and only studio album by American rapper Nipsey Hussle.",
                            Image = "",
                            Name = "Victory Lap",
                            Rating = "10/10"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 3,
                            Description = "The fourth studio album by American rapper Big Sean. It was released on February 3, 2017, through GOOD Music and distributed by Def Jam Recordings.",
                            Image = "",
                            Name = "I Decided",
                            Rating = "7.5/10"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 4,
                            Description = "The debut studio album by the Band. Released in 1968, it employs a distinctive blend of country, rock, folk, classical, R&B, blues, and soul.",
                            Image = "",
                            Name = "Music from Big Pink",
                            Rating = "10/10"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 5,
                            Description = "The second album by Crosby, Stills & Nash, and their first as a quartet with Neil Young. It was released in March 1970 by Atlantic Records.",
                            Image = "",
                            Name = "Déjà Vu",
                            Rating = "10/10"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "",
                            Name = "Dream Theater"
                        },
                        new
                        {
                            Id = 2,
                            Image = "",
                            Name = "Nipsey Hussle"
                        },
                        new
                        {
                            Id = 3,
                            Image = "",
                            Name = "Big Sean"
                        },
                        new
                        {
                            Id = 4,
                            Image = "",
                            Name = "The Band"
                        },
                        new
                        {
                            Id = 5,
                            Image = "",
                            Name = "Crosby, Stills, Nash & Young"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
